# -*- coding: utf-8 -*-
"""notebook32cac6c3dc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rndobuED-SOAzZK8ols2mDs7xvePYTXY
"""

!pip install -U -q docling

from huggingface_hub import login

login("hf_YOUR_TOKEN_HERE")

import pkgutil
import importlib
import inspect
import docling.datamodel

# for m in pkgutil.iter_modules(docling.datamodel.__path__):
#     mod = importlib.import_module(
#         f"docling.datamodel.{m.name}"
#     )

#     print(f"\n=== {m.name} ===")

#     for name, obj in inspect.getmembers(mod):
#         if inspect.isclass(obj):
#             print(name)

from docling.datamodel import vlm_model_specs

print(
    vlm_model_specs.GRANITEDOCLING_TRANSFORMERS.model_dump()
)

print(vlm_model_specs.GRANITEDOCLING_TRANSFORMERS)
print()
print(vlm_model_specs.GRANITE_VISION_TRANSFORMERS)

from docling.datamodel.pipeline_options import VlmConvertOptions, PdfPipelineOptions
import json
p = PdfPipelineOptions()
print(
    json.dumps(
        p.model_dump(mode="json"),
        indent=2,
        ensure_ascii=False
    )
)

from docling.document_converter import (
    DocumentConverter,
    PdfFormatOption,
)
from docling.pipeline.standard_pdf_pipeline import StandardPdfPipeline
from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions

pipeline_options = PdfPipelineOptions()

pipeline_options.do_ocr = True
pipeline_options.do_table_structure = True
pipeline_options.do_picture_description = False
pipeline_options.generate_page_images = True
pipeline_options.generate_picture_images = True
pipeline_options.do_formula_enrichment = True
pipeline_options.do_code_enrichment = True

converter = DocumentConverter(
    format_options={
        InputFormat.PDF: PdfFormatOption(
            pipeline_cls=StandardPdfPipeline,
            pipeline_options=pipeline_options,
        )
    }
)

# print(pipeline_options)
print("OCR:", pipeline_options.do_ocr)
print("Table:", pipeline_options.do_table_structure)
print("Picture Description:", pipeline_options.do_picture_description)

print("Generate Page Images:", pipeline_options.generate_page_images)
print("Generate Picture Images:", pipeline_options.generate_picture_images)

print("Formula Enrichment:", pipeline_options.do_formula_enrichment)
print("Code Enrichment:", pipeline_options.do_code_enrichment)

import gc
import torch
from docling_core.types.doc import ImageRefMode
pdf_path = "../input/datasets/khoayang/attention/1706.03762v7.pdf"
gc.collect()
torch.cuda.empty_cache()
result = converter.convert(pdf_path)

md = result.document.export_to_markdown()

# pdf_opt = converter.format_to_options[InputFormat.PDF]

# pic_opt = pdf_opt.pipeline_options.picture_description_options

# print(pic_opt.model_spec)

print(md)

from docling_core.types.doc import PictureItem

doc = result.document
for item, level in doc.iterate_items():
    if isinstance(item, PictureItem):
        # print(item)
        pass
pic = doc.pictures[0]
# ok
# print(pic.prov)
# print(pic.image)

for i, pic in enumerate(doc.pictures):
    image = pic.get_image(doc)

    print(image)
    image.save(f"figure_{i}.png")

for i, pic in enumerate(doc.pictures):
    print(pic.self_ref)
    print(pic.captions)

from PIL import Image
import matplotlib.pyplot as plt

for i in range(len(doc.pictures)):
    img = Image.open(f"figure_{i}.png")

    plt.figure(figsize=(6, 6))
    plt.imshow(img)
    plt.title(f"Figure {i}")
    plt.axis("off")
    plt.show()

doc.texts[2]

for t in doc.texts:
    if getattr(t.label, "value", "") == "caption":

        print("Caption:")
        print(t.text)

        print("Belongs to:")
        print(t.parent.cref)

        print()

text_map = {
    t.self_ref: t
    for t in doc.texts
}

for i, pic in enumerate(doc.pictures):

    p = pic.prov[0]

    print(
        i,
        p.page_no,
        p.bbox,
        bool(pic.captions)
    )

text_map = {
    t.self_ref: t
    for t in doc.texts
}

dataset = []

for pic in doc.pictures:

    img = pic.get_image(doc)

    caption = None

    if pic.captions:
        caption = text_map[pic.captions[0].cref].text

    dataset.append({
        "image": img,
        "caption": caption,
        "picture_ref": pic.self_ref,
        "page": pic.prov[0].page_no,
        "bbox": pic.prov[0].bbox
    })

dataset[0]

from transformers import AutoProcessor, Qwen2_5_VLForConditionalGeneration

model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2.5-VL-3B-Instruct",
    torch_dtype="auto",
    device_map="auto"
)

processor = AutoProcessor.from_pretrained(
    "Qwen/Qwen2.5-VL-3B-Instruct"
)

batch_messages = []
batch_images = [d["image"] for d in dataset]

SYSTEM_PROMPT = """
You are a helpful assistant.
"""

for image in batch_images:
    batch_messages.append([
        {
            "role": "system",
            "content": SYSTEM_PROMPT
        },
        {
            "role": "user",
            "content": [
                {"type": "image", "image": image},
                {"type": "text", "text": "Describe this figure."}
            ]
        }
    ])

texts = [
    processor.apply_chat_template(
        msg,
        tokenize=False,
        add_generation_prompt=True
    )
    for msg in batch_messages
]
processor.tokenizer.padding_side = "left"
inputs = processor(
    text=texts,
    images=batch_images,
    return_tensors="pt",
    padding=True
).to(model.device)

len(inputs)

generated_ids = model.generate(
    **inputs,
    max_new_tokens=512
)
generated_ids_trimmed = [
    out_ids[len(in_ids):]
    for in_ids, out_ids in zip(
        inputs.input_ids,
        generated_ids
    )
]
output_text = processor.batch_decode(
    generated_ids_trimmed,
    skip_special_tokens=True,
    clean_up_tokenization_spaces=False
)

print(output_text[0])

for i, desc in enumerate(output_text):
    replacement = f"""
![Figure {i}](images/figure_{i}.png)

**Visual Description**

{desc}
"""

    md = md.replace(
        "<!-- image -->",
        replacement,
        1
    )

print(md)

from docling.datamodel.pipeline_options import VlmPipelineOptions
from docling.datamodel import vlm_model_specs
from docling.document_converter import DocumentConverter, PdfFormatOption
from docling.pipeline.vlm_pipeline import VlmPipeline
from docling.datamodel.base_models import InputFormat

from copy import deepcopy

opt = deepcopy(
    vlm_model_specs.GRANITE_VISION_TRANSFORMERS
)

opt.scale = 1.0
opt.max_size = 1024
opt.max_new_tokens = 512

pipeline_options = VlmPipelineOptions(
    vlm_options=opt
)

pipeline_options.images_scale = 1.0

converter = DocumentConverter(
    format_options={
        InputFormat.PDF: PdfFormatOption(
            pipeline_cls=VlmPipeline,
            pipeline_options=pipeline_options,
        )
    }
)

print(pipeline_options)

from docling.datamodel.pipeline_options import VlmPipelineOptions

print(VlmPipelineOptions.model_fields.keys())

from docling.datamodel import vlm_model_specs

print(type(vlm_model_specs.GRANITE_VISION_TRANSFORMERS))

import gc
import torch
pdf_path = "../input/datasets/khoayang/attention/1706.03762v7.pdf"
gc.collect()
torch.cuda.empty_cache()
result = converter.convert(pdf_path)

md = result.document.export_to_markdown()

