"""
Markdown Enrichment module.

Replaces `<!-- image -->` placeholders in Docling-exported markdown
with actual figure images and VLM-generated visual descriptions.

Per Docling Skill: enrichment must be performed before chunking and embedding.
"""

from pathlib import Path


def enrich_markdown(
    md: str,
    descriptions: list[str],
    figure_paths: list[str],
    figures_base_dir: str = "figures",
) -> str:
    """
    Enrich markdown by replacing <!-- image --> placeholders with
    figure images and their VLM-generated descriptions.

    Per Docling Skill, the replacement format is:

        ![Figure N](images/figure_N.png)

        **Visual Description**

        <generated by Qwen3-VL>

    Args:
        md: Raw markdown string exported from Docling
        descriptions: List of VLM-generated descriptions for each figure
        figure_paths: List of absolute paths to figure images
        figures_base_dir: Relative directory name for image references

    Returns:
        Enriched markdown string
    """
    enriched = md

    for i, desc in enumerate(descriptions):
        # Build the image filename
        if i < len(figure_paths):
            img_name = Path(figure_paths[i]).name
        else:
            img_name = f"figure_{i}.png"

        replacement = (
            f"\n![Figure {i}]({figures_base_dir}/{img_name})\n\n"
            f"**Visual Description**\n\n"
            f"{desc}\n"
        )

        # Replace one <!-- image --> at a time (in order)
        enriched = enriched.replace("<!-- image -->", replacement, 1)

    return enriched


def count_image_placeholders(md: str) -> int:
    """Count the number of <!-- image --> placeholders in the markdown."""
    return md.count("<!-- image -->")


def save_markdown(md: str, output_path: str) -> str:
    """Save markdown content to a file."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(md, encoding="utf-8")
    return str(path)
